mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import login, logout

from . import views as app_views

app_name = 'polls'
urlpatterns = [
    path('', app_views.index, name='index'),
    path('signup/', app_views.SignUpView.as_view(), name='signup'),
    path('beneficiario/', app_views.beneficiario, name='beneficiario'),
    path('resumen/<int:user_index>', app_views.resumen, name='resumen'),
    path('detalle/<int:beneficiario_id>', app_views.detalle, name='detalle'),
    path('detalle_observaciones/<int:pk>/', app_views.detalle_observaciones, name='detalle_observaciones'),
    path('familia/<int:pk>/', app_views.familia, name='familia'),
    path('excelreport/<int:user_index>', app_views.excelreport, name='excelreport'),
    path('grupofamiliar/<int:pk>/', app_views.grupofamiliar, name='grupofamiliar'),
    path('grupofamiliar_post_conv/<int:pk>/', app_views.grupofamiliar_post_conv, name='grupofamiliar_post_conv'),
    path('grupofamiliar_post_no_conv/<int:pk>/', app_views.grupofamiliar_post_no_conv, name='grupofamiliar_post_no_conv'),
    path('grupofamiliar_terminar/<int:pk>/', app_views.grupofamiliar_terminar, name='grupofamiliar_terminar'),
    path('upload_img/<int:beneficiario_id>/<int:question_id>/', app_views.upload_img, name='upload_img'),
    path('dnifotos/<int:beneficiario_id>/', app_views.dnifotos, name='dnifotos'),
    path('<int:pk>/<int:question_id>/', app_views.detail, name='detail'),
    path('<int:pk>/<int:question_id>/results/', app_views.results, name='results'),
    path('<int:pk>/<int:question_id>/vote/', app_views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.db.models import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User


class TipoDePlan(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


# datos sociales sobre un beneficiario.
# por ahora omitir grupo familiar; solamente
# el que esta a cargo y eso.
class BeneficiarioFamilia(models.Model):
    CANTIDAD_HOGARES_CHOICES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
    ]
    ESTADO_CIVIL_CHOICES = [
        ('soltero', 'SOLTERO/A'),
        ('casado', 'CASADO/A'),
        ('divorciado', 'DIVORCIADO/A'),
        ('en-pareja', 'EN PAREJA/CONCUBINATO'),
        ('separado', 'SEPARADO/A DE HECHO'),
        ('viudo', 'VIUDO/A'),
    ]
    TIPO_DOCUMENTO_CHOICES = [
        ('libreta-civica', 'Libreta Civica'),
        ('libreta-de-enrolamiento', 'Libreta De enrolamiento'),
        ('dni', 'DNI'),
        ('doc-extranjero', 'Doc. Extranjero'),
        ('nunca-tuvo', 'Nunca Tuvo'),
        ('otro', 'Otro'),
    ]
    IDENTIDAD_DE_GENERO_CHOICES = [
        ('Mujer', 'Mujer'),
        ('Varón', 'Varón'),
        ('Disidencia', 'Disidencia'),
    ]
    PARENTESCO_CHOICES = [
        ('Jefe', 'Jefe'),
        ('Cónyuge/pareja', 'Cónyuge/pareja'),
        ('Hijo/a', 'Hijo/a'),
        ('Yerno/nuera', 'Yerno/nuera'),
        ('Nieto/a', 'Nieto/a'),
        ('Padre/madre', 'Padre/madre'),
        ('Suegro/a', 'Suegro/a'),
        ('Otro familiar', 'Otro familiar'),
        ('No familiar', 'No familiar'),
    ]
    TRABAJO_REMUNERADO_CHOICES = [
        ('Formal', 'Formal'),
        ('Informal', 'Informal'),
        ('Autónomo', 'Autónomo'),
        ('Jubilación/retiro', 'Jubilación/retiro'),
        ('Desocupado', 'Desocupado'),
    ]
    OTROS_INGRESOS_CHOICES = [
        ('AUH', 'AUH'),
        ('AUE', 'AUE'),
        ('Tarjeta Alimentar', 'Tarjeta Alimentar'),
        ('Potenciar Inclusión Joven', 'Potenciar Inclusión Joven'),
        ('Argentina Hace', 'Argentina Hace'),
        ('Potenciar Trabajo', 'Potenciar Trabajo'),
        ('Fondo Desempleo', 'Fondo Desempleo'),
        ('Pensión Madre de 7 hijos', 'Pensión Madre de 7 hijos'),
        ('Pensión por discapacidad', 'Pensión por discapacidad'),
        ('IFE', 'IFE'),
        ('Otros', 'Otros'),
    ]
    COBERTURA_DE_SALUD_CHOICES = [
        ('No posee', 'No posee'),
        ('Pre paga', 'Pre paga'),
        ('APROSS', 'APROSS'),
        ('PAMI', 'PAMI'),
        ('PROFE', 'PROFE'),
        ('Otros', 'Otros'),
    ]
    DISCAPACIDAD_CHOICES = [
        ('No', 'No'),
        ('Motriz', 'Motriz'),
        ('Intelectual', 'Intelectual'),
        ('Sensorial', 'Sensorial'),
        ('Multidiscapacidad', 'Multidiscapacidad'),
    ]
    CERTIFICADO_DE_DISCAPACIDAD_CHOICES = [
        ('Si, Vigente', 'Si, Vigente'),
        ('Si, No vigente', 'Si, No Vigente'),
        ('En trámite', 'En trámite'),
        ('No', 'No'),
    ]

    # datos del hogar
    cantidad_hogares = models.CharField(max_length=120, choices=CANTIDAD_HOGARES_CHOICES, default='1')
    numero_de_hogar = models.CharField(max_length=120, choices=CANTIDAD_HOGARES_CHOICES, default='1')

    # datos del jefe/a
    jefe_apellido = models.CharField(max_length=120)
    jefe_nombre = models.CharField(max_length=120)
    jefe_tipo_documento = models.CharField(max_length=120, choices=TIPO_DOCUMENTO_CHOICES, default='dni')
    jefe_numero_documento = models.IntegerField()
    jefe_fecha_nacimiento = models.DateField()
    jefe_edad = models.IntegerField()
    jefe_telefono = models.CharField(max_length=50)
    jefe_contacto = models.CharField(max_length=100, blank=True, default="")
    jefe_estado_civil = models.CharField(max_length=100, choices=ESTADO_CIVIL_CHOICES)
    jefe_nacionalidad = models.CharField(max_length=120)
    jefe_personas_en_hogar = models.IntegerField()
    jefe_identidad_de_genero = models.CharField(max_length=80, verbose_name="Identidad de género",
                                                choices=IDENTIDAD_DE_GENERO_CHOICES)
    jefe_estudios_alcanzados = models.CharField(verbose_name="Estudios alcanzados", max_length=50)
    jefe_trabajo_remunerado = models.CharField(max_length=80, choices=TRABAJO_REMUNERADO_CHOICES, verbose_name="Trabajo remunerado")
    jefe_ingresos_por_trabajo = models.IntegerField(verbose_name="Ingresos por trabajo")
    jefe_planes = models.ManyToManyField(TipoDePlan, verbose_name="Planes sociales")
    jefe_otros_ingresos = models.CharField(max_length=200, verbose_name="Otros ingresos", blank=True, default="")
    jefe_cobertura_de_salud = models.CharField(max_length=80, choices=COBERTURA_DE_SALUD_CHOICES, verbose_name="Cobertura de salud")
    jefe_discapacidad = models.CharField(max_length=80, choices=DISCAPACIDAD_CHOICES, verbose_name="Discapacidad")
    jefe_certificado_de_discapacidad = models.CharField(max_length=80, choices=CERTIFICADO_DE_DISCAPACIDAD_CHOICES,
                                                        default="No", verbose_name="Certificado de discapacidad")
    jefe_enfermedad_cronica = models.CharField(max_length=80, verbose_name="Enfermedad Crónica", default="No")
    jefe_embarazo_en_curso = models.BooleanField(default=False, verbose_name="Embarazo en curso")

    # datos del niño/a
    nino_apellido = models.CharField(max_length=120, verbose_name="Apellido")
    nino_nombre = models.CharField(max_length=120, verbose_name="Nombre")
    nino_tipo_documento = models.CharField(max_length=120, choices=TIPO_DOCUMENTO_CHOICES, default='dni', verbose_name="Tipo de documento")
    nino_numero_documento = models.IntegerField(verbose_name="Número de documento")
    nino_fecha_nacimiento = models.DateField(verbose_name="Fecha de nacimiento")
    nino_edad = models.IntegerField(verbose_name="Edad")
    nino_otros_ingresos = models.CharField(max_length=200, verbose_name="Otros ingresos", blank=True, default="")
    nino_identidad_de_genero = models.CharField(max_length=80, verbose_name="Identidad de género",
                                                choices=IDENTIDAD_DE_GENERO_CHOICES)
    nino_educacion = models.CharField(max_length=120, verbose_name="Educación")
    nino_parentesco = models.CharField(max_length=80, verbose_name="Parentezco c/jefe/a flia")
    nino_cobertura_de_salud = models.CharField(max_length=80, choices=COBERTURA_DE_SALUD_CHOICES, verbose_name="Cobertura de salud")
    nino_discapacidad = models.CharField(max_length=80, choices=DISCAPACIDAD_CHOICES, verbose_name="Discapacidad")
    nino_certificado_de_discapacidad = models.CharField(max_length=80, choices=CERTIFICADO_DE_DISCAPACIDAD_CHOICES,
                                                        default="No", verbose_name="Certificado de discapacidad")
    nino_enfermedad_cronica = models.CharField(max_length=80, verbose_name="Enfermedad Crónica", default="No")


# sobre quien es la encuesta.
class Beneficiario(models.Model):
    # usuario que registro el beneficiario
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    # entrevistador
    entrevistador_nombre_apellido = models.CharField(max_length=100, help_text="Nombre y apellido del entrevistador",
                                                     default="")
    entrevistador_fecha = models.DateField(help_text="Fecha", auto_now_add=True)

    # datos generales del inmueble
    inm_calle = models.CharField(max_length=256, help_text="Calle", default="")
    inm_numero = models.IntegerField(help_text="Número", default=0)
    inm_barrio = models.CharField(max_length=256, help_text="Barrio", default="")
    inm_localidad = models.CharField(max_length=100, help_text="Localidad", default="")
    inm_departamento = models.CharField(max_length=100, help_text="Departament", default="")
    inm_lat = models.DecimalField(max_digits=22, decimal_places=16, blank=True, default=0)
    inm_lng = models.DecimalField(max_digits=22, decimal_places=16, blank=True, default=0)
    inm_codigo_postal = models.CharField(max_length=60, default="")

    # entrevista efectiva
    ENTREVISTA_EFECTIVA_CHOICES = [
        ('si', 'Si'),
        ('rechazo', 'No: Rechazo'),
        ('lote-baldio', 'No: Lote Baldío'),
        ('se-mudo', 'No: Se mudó'),
        ('otros', 'No: Otros'),
    ]
    entrevista_efectiva = models.CharField(choices=ENTREVISTA_EFECTIVA_CHOICES, max_length=100)

    # beneficiario familia
    familia = models.OneToOneField(
        BeneficiarioFamilia,
        on_delete=models.CASCADE,
        null=True,
    )

    terminado_datos_familia = models.BooleanField(default=False)
    observaciones = models.CharField(max_length=3000, default="")


# Define un conviviente de un beneficiario
class MiembroConviviente(models.Model):
    ESTADO_CIVIL_CHOICES = [
        ('soltero', 'SOLTERO/A'),
        ('casado', 'CASADO/A'),
        ('divorciado', 'DIVORCIADO/A'),
        ('en-pareja', 'EN PAREJA/CONCUBINATO'),
        ('separado', 'SEPARADO/A DE HECHO'),
        ('viudo', 'VIUDO/A'),
    ]
    TIPO_DOCUMENTO_CHOICES = [
        ('libreta-civica', 'Libreta Civica'),
        ('libreta-de-enrolamiento', 'Libreta De enrolamiento'),
        ('dni', 'DNI'),
        ('doc-extranjero', 'Doc. Extranjero'),
        ('nunca-tuvo', 'Nunca Tuvo'),
        ('otro', 'Otro'),
    ]
    IDENTIDAD_DE_GENERO_CHOICES = [
        ('Mujer', 'Mujer'),
        ('Varón', 'Varón'),
        ('Disidencia', 'Disidencia'),
    ]
    PARENTESCO_CHOICES = [
        ('Jefe', 'Jefe'),
        ('Cónyuge/pareja', 'Cónyuge/pareja'),
        ('Hijo/a', 'Hijo/a'),
        ('Yerno/nuera', 'Yerno/nuera'),
        ('Nieto/a', 'Nieto/a'),
        ('Padre/madre', 'Padre/madre'),
        ('Suegro/a', 'Suegro/a'),
        ('Otro familiar', 'Otro familiar'),
        ('No familiar', 'No familiar'),
    ]
    TRABAJO_REMUNERADO_CHOICES = [
        ('Formal', 'Formal'),

polls/templates/polls/beneficiario.html
{% extends 'polls/base.html' %}

{% block title %}Domicilio{% endblock %}

{% block content %}

    <style>
    input[type=text], input[type=number] {
        display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }

    select, textarea {
        width: 100%;
    }
    #map {
        height: 300px;
    }

    h3 {
        margin-top: 30px;
        margin-bottom: 30px;
    }
    </style>

    {% if error %}<p><strong class="text-danger">{{ error }}</strong></p>{% endif %}

    <div class="container">
        <form action="{% url 'polls:beneficiario' %}" method="post">
            {% csrf_token %}

        <h3>Añadir domicilio</h3>
            {% for field in form %}
                <div class="form-group">
                    <!-- Insertar categorias -->
                    {% if field.label == "Calle" %}
                        <h3>Datos generales de la ubicación del inmueble</h3>
                    {% endif %}
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {% if field.help_text %}
                        <p class="text-muted">{{ field.help_text|safe }}</p>
                    {% endif %}
                    {{ field }}
                </div>
            {% endfor %}

            <h3>Ubique el inmueble en el mapa.</h3>
            <button class="btn btn-outline-secondary btn-block my-2" onclick="return setToCurrentPos(true)"><i class="fa fa-map-marker"></i> Marcar ubicación actual</button>
            <div id="map"></div>
            <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAmOfy_ZrunHS24lMG9-QA-Eqnc3PVZOUU&callback=initMap"></script>
            <br>
            <button type="submit" class="btn btn-primary btn-block">Registrar</button>
        </form>
    </div>

    <script>
        var map, marker;

        function selectPos(latLng, center) {
            if (marker) marker.setMap(null);
            marker = new google.maps.Marker({
                position: latLng,
                map: map,
                title: 'Ubicación'
            });
            let latElem = document.getElementById("id_inm_lat");
            let lngElem = document.getElementById("id_inm_lng");
            if (latElem) latElem.setAttribute("value", latLng.lat.toFixed(4));
            if (lngElem) lngElem.setAttribute("value", latLng.lng.toFixed(4));
            if (map && center) {
                map.setCenter(latLng);
            }
        }

        function setToCurrentPos(center) {
            // Try HTML5 geolocation.
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };
                    selectPos(pos, center);
                }, function(err) {
                    /*alert(
                        "Necesita permitir la ubicación, puede recargar la página para que se le vuelva a preguntar.\n" +
                        "Error: " + err.message
                    )*/
                });
            } else {
                alert("Este navegador no soporta geolocalización.")
            }
            return false;
        }

        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -31.41, lng: -64.183},
                zoom: 14
            });

            google.maps.event.addListener(map, 'click', function(event) {
                var myLatlng = new google.maps.LatLng(event.latLng.lat(),event.latLng.lng() );
                selectPos({ lat: event.latLng.lat(), lng: event.latLng.lng() }, false);
            });

            setToCurrentPos(true);
        }

    </script>
{% endblock %}

polls/templates/polls/detalle.html
<head>
    <link rel="stylesheet" href="/static/polls/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        body {
        }

        tr{ font-size: 80%; }
        th{ font-size: 80%; }
        h2 {
            background: lightgray;
            width: 100%;
            margin-top: 80px;
            margin-bottom: 40px;
        }
        h3 {
            margin-top: 30px;
        }
    </style>

</head>

<body>

<div class="">

    <button class="btn-block w-100 btn btn-warning" onclick="
    console.log(this);
    this.style.setProperty('visibility', 'hidden');
    let botonsave = document.getElementById('botonsave');
    botonsave.style.setProperty('visibility', 'hidden');
    setTimeout(() => {
        this.style.setProperty('visibility', 'visible');
        if (botonsave) botonsave.style.setProperty('visibility', 'visible');
    }, 2000);
    this.visibility='hidden';
    window.print();
    return false;
    "><i class="fa fa-print"></i> Imprimir</button>

<img src="/static/polls/header.png" style="width: 100%;
    transform: scale(0.5);
    text-align: left;"/>


<div class="col">
    <h1 class="w-100 text-center">PROGRAMA DE AYUDAS URGENTES</h1>
    <h2 class="w-100 text-center">DATOS GENERALES</h2>

    <h3 class="w-100">Solicitante</h3>

    Apellido/s: <b>{{ f.jefe_apellido }}</b><br>
    Nombre: <b>{{ f.jefe_nombre }}</b><br>
    Documento de identidad, tipo: <b>{{ f.get_jefe_tipo_documento_display }}</b><br>
    DNI N°: <b>{{ f.jefe_numero_documento }}</b><br>
    Fecha de nacimiento: <b>{{ f.jefe_fecha_nacimiento|date:'d/m/Y' }}</b><br>
    Edad: <b>{{ f.jefe_edad }}</b><br>
    Nacionalidad: <b>{{ f.jefe_nacionalidad }}</b><br>
    Estado civil: <b>{{ f.get_jefe_estado_civil_display }}</b><br>

    <h3 class="w-100">Domicilio</h3>
    Calle: <b>{{ b.inm_calle }}</b><br>
    Numero: <b>{{ b.inm_numero }}</b><br>
    Barrio: <b>{{ b.inm_barrio }}</b><br>
    Localidad: <b>{{ b.inm_localidad }}</b><br>
    CP: <b>{{ b.inm_codigo_postal }}</b><br>
    Departamento: <b>{{ b.inm_departamento }}</b><br>
    Teléfono: <b>{{ f.jefe_telefono }}</b><br>
    Teléfono alternativo: <b>{{ f.jefe_contacto }}</b><br>
    Entrevista efectiva: <b>{{ b.entrevista_efectiva }}</b><br>
    Entrevistador: <b>{{ b.entrevistador_nombre_apellido }}</b><br>
    Fecha: <b>{{ b.entrevistador_fecha|date:'d/m/Y' }}</b><br>

    <h2 class="w-100 text-center text-uppercase">RELEVAMIENTO SOCIAL</h2>

    <h3>Cantidad de integrantes de la familia</h3>
    Personas en el hogar: <b>{{ f.jefe_personas_en_hogar }}</b><br>
    Cantidad de hogares: <b>{{ f.cantidad_hogares }}</b><br>
    Numero de hogar: <b>{{ f.numero_de_hogar }}</b><br>

    <h3>Sobre el niño/a</h3>
    <ul>
        <li>Apellido: <b>{{ f.nino_apellido }}</b></li>
        <li>Nombre: <b>{{ f.nino_nombre }}</b></li>
        <li>Tipo de documento: <b>{{ f.get_nino_tipo_documento_display }}</b></li>
        <li>Número de documento: <b>{{ f.nino_numero_documento }}</b></li>
    </ul>

    {% if dniFotos is not None %}
        <h3>DNI del jefe/a de familia</h3>
            <img src="{{ dniFotos.jefe_foto_dorso.url }}" alt="" width="400px">
            <img src="{{ dniFotos.jefe_foto_frente.url }}" alt="" width="400px">
        <h3>DNI del niño/a</h3>
            <img src="{{ dniFotos.nino_foto_dorso.url }}" alt="" width="400px">
            <img src="{{ dniFotos.nino_foto_frente.url }}" alt="" width="400px">

    {% endif %}

    <h3 class="w-100">Datos del grupo familiar conviviente</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Documento</th>
            <th scope="col">Edad</th>
            <th scope="col">Identidad de género</th>
            <th scope="col">Parentezco c/jefe/a flia</th>
            <th scope="col">Estado civil</th>
            <th scope="col">Estudios alcanzados</th>
            <th scope="col">Trabajo remunerado</th>
            <th scope="col">Ingresos por trabajo</th>
            <th scope="col">Planes sociales</th>
            <th scope="col">Otros ingresos</th>
            <th scope="col">Cobertura de salud</th>
            <th scope="col">Discapacidad</th>
            <th scope="col">Enf. Crónica</th>
            <th scope="col">Embarazo en curso</th>
        </tr>
        </thead>
        <tbody>
        {% for f in convivientes %}
            <tr>
                <td>{{ f.nombre }}</td>
                <td>{{ f.apellido }}</td>
                <td>{{ f.get_tipo_de_documento_display }} {{ f.numero_de_documento }}</td>
                <td>{{ f.edad }}</td>
                <td>{{ f.identidad_de_genero }}</td>
                <td>{{ f.parentesco }}</td>
                <td>{{ f.get_estado_civil_display }}</td>
                <td>{{ f.estudios_alcanzados }}</td>
                <td>{{ f.trabajo_remunerado }}</td>
                <td>${{ f.ingresos_por_trabajo }}</td>
                <td>
                    {% for p in f.planes.all %}
                        {{ p.nombre }},
                    {% endfor %}
                </td>
                <td>{{ f.otros_ingresos }}</td>
                <td>{{ f.cobertura_de_salud }}</td>
                <td>{{ f.discapacidad }} ({{ f.certificado_de_discapacidad }})</td>
                <td>{{ f.enfermedad_cronica }}</td>
                <td>{{ f.embarazo_en_curso|yesno:"Si,No" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <h3 class="w-100">Datos del grupo familiar no conviviente</h3>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellido</th>
            <th scope="col">Observaciones</th>
        </tr>
        </thead>
        <tbody>
        {% for f in no_convivientes %}
            <tr>
                <td>{{ f.nombre }}</td>
                <td>{{ f.apellido }}</td>
                <td>{{ f.observaciones }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <h2 class="w-100 text-uppercase text-center">RELEVAMIENTO FISICO-AMBIENTAL</h2>

    <!-- Renderizar lista -->
    <ul>
        {% for q in qa %}
            <!-- Titulos de categorias -->
            {% if q.q == 'Baño' %}
                <h3>Baño</h3>
            {% elif q.q == '¿Dispone de un espacio para cocinar/comer?' %}
                <h3>Cocina</h3>
            {% elif q.q == 'Tenencia' %}
                <h3>Sobre la vivienda</h3>
            {% elif q.q == '¿Dispone de un espacio para cocinar/comer?' %}
                <h3>Cocina</h3>
            {% elif q.q == 'Servicios / Agua potable' %}
                <h3>Servicios</h3>
            {% endif %}

            <!-- Nombre del item -->
            <li>{{ q.q }}: <b>{{ q.a }}</b></li>

            <!-- Imagen -->
            {% if q.img %}
                <img src="{{ q.img.url }}" alt="" width="200px">
            {% endif %}

        {% endfor %}
    </ul>

    <h2 class="text-uppercase w-100 text-center">Conclusiones generales y sugerencias de intervención</h2>

    {% if permitirGuardarDescripcion %}
        <form action="{% url 'polls:detalle_observaciones' pk %}" method="post">
            {% csrf_token %}
            <textarea rows="10" class="w-100" required name="observaciones">{{ b.observaciones }}</textarea>
            <br><br>
            <button type="submit" id="botonsave" class="btn btn-danger btn-block py-3"><i class="fa fa-save"></i> Guardar y finalizar observación</button>
        </form>
        <div class="row">
            <div class="col-4">FIRMA DEL TRABAJADOR SOCIAL</div>
            <div class="col-4">SELLO</div>
            <div class="col-4">DNI</div>
        </div>
    {% else %}
        <textarea rows="10" class="w-100">{{ b.observaciones }}</textarea>
        <div class="row">
            <div class="col-4">FIRMA DEL TRABAJADOR SOCIAL</div>
            <div class="col-4">SELLO</div>
            <div class="col-4">DNI</div>
        </div>
    {% endif %}


</div>
<br>
<br>
<br>
<br>
<br>

</div>

</body>

polls/templates/polls/dnifotos.html
{% extends 'polls/base.html' %}

{% block title %}Fotos del DNI{% endblock %}

{% block content %}

    <style>
    input[type=text], input[type=number] {
        display: block;
        width: 100%;
        height: calc(1.5em + .75rem + 2px);
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }
    label {
        white-space: pre-wrap;
        padding-top: 10px;
        padding-bottom: 10px;
    }

    select, textarea {
        width: 100%;
    }

    h3 {
        margin-top: 30px;
        margin-bottom: 30px;
    }
    </style>

    {% if error %}<p><strong class="text-danger">{{ error }}</strong></p>{% endif %}

    <div class="container">
        <form action="{% url 'polls:dnifotos' pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h1>Subir fotos del DNI</h1>
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block m">Subir</button>
        </form>
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block title %}información{% endblock %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}